### PR TITLE
add project urls and descriptions (resolves #1)

### LINKED ISSUE #1: Read https://gnu.moe/list/nocommands.html into this repository
This will be the first step. We can get URLs from there.

### PR DESCRIPTION
**Pull request by dohliam**
Added links and descriptions. Long descriptions sourced from apt-cache.

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
Holy shit, this is a huge diff! Would you care to make this into one-file-one-commit, or would it be too much effort for you (you can script this!)?

**Comment by dohliam** [comment]
Sure, I don't think that would be too difficult, so long as you don't mind a PR for 481 commits... :smile: 

I'll roll back this single huge commit and replace it with one commit per file.

**Comment by matthiasbeyer** [comment]
Awesome! No, many commits is better because I can roll back individually if required. Thank you a lot!

**Comment by dohliam** [comment]
Done and new PR (#13) submitted!

**Pull request closed without merging**
